// Auto-generated
let project = new Project('SpaceShooterblend');

project.addSources('Sources');
project.addLibrary("/Users/kent/Applications/Armory/blender.app/armsdk/armory");
project.addLibrary("/Users/kent/Applications/Armory/blender.app/armsdk/iron");
project.addLibrary("/Users/kent/Applications/Armory/blender.app/armsdk/lib/haxebullet");
project.addAssets("/Users/kent/Applications/Armory/blender.app/armsdk/lib/haxebullet/js/ammo/ammo.js", { notinlist: true });
project.addParameter('arm.BulletController');
project.addParameter("--macro keep('arm.BulletController')");
project.addParameter('arm.PlayerController');
project.addParameter("--macro keep('arm.PlayerController')");
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addParameter('arm.EnemyController');
project.addParameter("--macro keep('arm.EnemyController')");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addShaders('/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Shaders/blur_edge_pass.frag.glsl');
project.addShaders('/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Shaders/compositor_pass.frag.glsl');
project.addShaders('/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Shaders/compositor_pass.vert.glsl');
project.addShaders('/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Shaders/deferred_indirect.frag.glsl');
project.addShaders('/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Shaders/deferred_indirect.vert.glsl');
project.addShaders('/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Shaders/deferred_light.frag.glsl');
project.addShaders('/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Shaders/deferred_light_quad.frag.glsl');
project.addShaders('/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Shaders/pass.vert.glsl');
project.addShaders('/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Shaders/pass_lamp_volume.vert.glsl');
project.addShaders('/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Shaders/pass_viewray.vert.glsl');
project.addShaders('/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Shaders/smaa_blend_weight.frag.glsl');
project.addShaders('/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Shaders/smaa_blend_weight.vert.glsl');
project.addShaders('/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Shaders/smaa_edge_detect.frag.glsl');
project.addShaders('/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Shaders/smaa_edge_detect.vert.glsl');
project.addShaders('/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Shaders/smaa_neighborhood_blend.frag.glsl');
project.addShaders('/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Shaders/smaa_neighborhood_blend.vert.glsl');
project.addShaders('/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Shaders/ssao_pass.frag.glsl');
project.addShaders('/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Shaders/world_pass.frag.glsl');
project.addShaders('/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Shaders/world_pass.vert.glsl');
project.addShaders('build_SpaceShooterblend/compiled/Shaders/Material_003_mesh.frag.glsl');
project.addShaders('build_SpaceShooterblend/compiled/Shaders/Material_003_mesh.vert.glsl');
project.addShaders('build_SpaceShooterblend/compiled/Shaders/Material_003_shadowmap.frag.glsl');
project.addShaders('build_SpaceShooterblend/compiled/Shaders/Material_003_shadowmap.vert.glsl');
project.addShaders('build_SpaceShooterblend/compiled/Shaders/armdefault_mesh.frag.glsl');
project.addAssets("build_SpaceShooterblend/compiled/Shaders/Material_003_data.arm", { notinlist: true });
project.addAssets("build_SpaceShooterblend/compiled/Shaders/armdefault_data.arm", { notinlist: true });
project.addAssets("build_SpaceShooterblend/compiled/Shaders/shader_datas.arm", { notinlist: true });
project.addAssets("/Users/kent/Applications/Armory/blender.app/armsdk/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("/Users/kent/Applications/Armory/blender.app/armsdk/armory/Assets/noise8.png", { notinlist: true });
project.addAssets("/Users/kent/Applications/Armory/blender.app/armsdk/armory/Assets/smaa_area.png", { notinlist: true });
project.addAssets("/Users/kent/Applications/Armory/blender.app/armsdk/armory/Assets/smaa_search.png", { notinlist: true });
project.addAssets("/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Assets/Scene.arm", { notinlist: true });
project.addAssets("/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Assets/meshes/mesh_Cube.006.arm", { notinlist: true });
project.addAssets("/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Assets/meshes/mesh_Cube.arm", { notinlist: true });
project.addAssets("/Users/kent/Desktop/Space Shooter/build_SpaceShooterblend/compiled/Assets/meshes/mesh_Cylinder.002.arm", { notinlist: true });
project.addAssets("build_SpaceShooterblend/compiled/Assets/envmaps/World_irradiance.arm", { notinlist: true });
project.addDefine('arm_deferred');
project.addDefine('arm_csm');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_depthprepass');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_size=1024');
project.addDefine('rp_background=World');
project.addDefine('rp_render_to_texture');
project.addDefine('rp_compositornodes');
project.addDefine('rp_antialiasing=SMAA');
project.addDefine('rp_supersampling=1');
project.addDefine('rp_gi=Off');
project.addDefine('rp_ssgi=SSAO');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_shaderload');
project.addDefine('arm_soundcompress');
project.addDefine('arm_skin');
project.addDefine('arm_fast');


resolve(project);
